<?php
/**
 * @category   Emartech
 * @package    Emartech_EmarsysRecommender
 * @copyright  Copyright (c) 2018 Emarsys. (http://www.emarsys.net/)
 */

/** @var \Emartech\EmarsysRecommender\Block\JavascriptTracking $block */
?>
<script>ScarabQueue.push(["cart", [<?php echo $block->getCartItemsJsonData() ?>]]);</script>
<?php $pageHandleData = $block->getPageHandleStatus(); ?>
<?php if ($pageHandleData['status'] == 'Valid' && $pageHandleData['logic'] != ''): ?>
    <script>
        function localizePrice(SC) {
            for (var i=0; i < SC.page.products.length; i++) {
                SC['page']['products'][i].price_formatted = SC['page']['products'][i].price.toMoney(2, '.' , ',' ) ;
            }
        }

        Number.prototype.toMoney = function(decimals, decimal_sep, thousands_sep) {
            var n = this,
                c = isNaN(decimals) ? 2 : Math.abs(decimals), //if decimal is zero we must take it, it means user does not want to show any decimal
                d = decimal_sep || '.', //if no decimal separator is passed we use the dot as default decimal separator (we MUST use a decimal separator)

                /*
                according to [https://stackoverflow.com/questions/411352/how-best-to-determine-if-an-argument-is-not-sent-to-the-javascript-function]
                the fastest way to check for not defined parameter is to use typeof value === 'undefined'
                rather than doing value === undefined.
                */
                t = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep, //if you don't want to use a thousands separator you can pass empty string as thousands_sep value

                sign = (n < 0) ? '-' : '',

                //extracting the absolute value of the integer part of the number and converting to string
                i = parseInt(n = Math.abs(n).toFixed(c)) + '',

                j = ((j = i.length) > 3) ? j % 3 : 0;
            return sign + (j ? i.substr(0, j) + t : '') + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : '');
        }
    </script>
    <?php if ($pageHandleData['logic'] != 'HOME_'): ?>
        <?php if ($pageHandleData['logic'] == 'DEPARTMENT'): ?>
            <div id="dept1"></div>
            <div id="dept2"></div>
            <div id="dept3"></div>
            <div id="dept4"></div>
            <div id="dept5"></div>
            <div id="dept6"></div>
            <div id="dept7"></div>
            <div id="dept8"></div>
            <div id="dept9"></div>
            <div id="dept10"></div>
            <script type="text/html" id="<?php echo $pageHandleData['templateId']; ?>">
                <![CDATA[
                <h4>{{=SC.title}}</h4>
                {{ for (var i=0; i < SC.page.products.length; i++) { }}
                {{ var p = SC.page.products[i]; }}
                <span data-scarabitem="{{= p.id }}" style="display: inline-block" class="rec-item">
                    <a href="{{=p.link}}" target="_blank"><img src="{{=p.image}}" class="rec-image" title="{{= p.title}}"></a>
                </span>
                <span id="format_{{=i}}">{{=p.price_formatted}}</span>
                {{ } }}
                ]]>
            </script>
            <script>
                for (var i = 1; i < 11; i++) {
                    ScarabQueue.push(['recommend', {
                        logic: 'DEPARTMENT_' + i,
                        limit: 5,
                        containerId: 'dept' + i,
                        templateId: '<?php echo $pageHandleData['templateId']; ?>',
                        success: function (SC, render) {
                            if (SC.topicLocalized) {
                                SC.title = SC.topicLocalized.replace(/Root Catalog>/g, '');
                                localizePrice(SC);
                                render(SC);
                            }
                        }
                    }]);
                }
            </script>
        <?php endif; ?>

        <?php if ($pageHandleData['logic'] != 'DEPARTMENT'): ?>
            <div id="recommended-product"></div>
            <script type="text/html" id="<?php echo $pageHandleData['templateId']; ?>">
                <![CDATA[
                {{ if (SC.page.products.length) { }}
                <div class="scarab-itemlist">
                    <div class="scarab-prev">◀</div>
                    {{ for (var i=0; i < SC.page.products.length; i++) { }}
                    {{ var p = SC.page.products[i]; }}
                    <span data-scarabitem="{{= p.id }}" class="scarab-item">
                        <a href="{{= p.link }}"><img src="{{= p.image }}" class="rec-image" title="{{= p.title}}">{{= p.title }}</a>
                    </span>
                    {{ } }}
                    <div class="scarab-next">▶</div>
                </div>
                {{ } }}
                ]]>
            </script>
            <script>
                ScarabQueue.push(['recommend', {
                    logic: '<?php echo $pageHandleData["logic"]; ?>',
                    limit: '6',
                    containerId: 'recommended-product',
                    templateId: '<?php echo $pageHandleData['templateId']; ?>'
                }]);
            </script>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($pageHandleData['logic'] == "HOME_"): ?>
        <div id="home1"></div>
        <div id="home2"></div>
        <div id="home3"></div>
        <div id="home4"></div>
        <div id="home5"></div>
        <div id="home6"></div>
        <div id="home7"></div>
        <div id="home8"></div>
        <div id="home9"></div>
        <div id="home10"></div>
        <script type="text/html" id="<?php echo $pageHandleData['templateId'] ?>">
            <![CDATA[
            <h4>{{=SC.title}}</h4>
            {{ for (var i=0; i < SC.page.products.length; i++) { }}
            {{ var p = SC.page.products[i]; }}
            <span data-scarabitem="{{= p.id }}" style="display: inline-block" class="rec-item">
                <a href="{{=p.link}}" target="_blank"><img src="{{=p.image}}" class="rec-image" title="{{= p.title}}"></a>
            </span>
            <span id="format_{{=i}}">{{=p.price_formatted}}</span>
            {{ } }}
            ]]>
        </script>
        <script>
            for (var i = 1; i < 11; i++) {
                ScarabQueue.push(['recommend', {
                    logic: '<?php echo $pageHandleData['logic'] ?>' + i,
                    limit: 6,
                    containerId: 'home' + i,
                    templateId: '<?php echo $pageHandleData['templateId'] ?>',
                    success: function (SC, render) {
                        if (SC.topicLocalized) {
                            SC.title = SC.topicLocalized.replace(/Root Catalog>/g, '');
                            localizePrice(SC);
                            render(SC);
                        }
                    }
                }]);
            }
        </script>
    <?php endif; ?>
    <style>
        .rec-item {
            text-align: center;
        }

        .rec-image {
            max-width: 80px;
            max-height: 80px;
        }

        .scarab-itemlist {
            padding: 0px 20px;
            position: relative;
            border: 1px solid #C5D7EF;
        }

        .scarab-item {
            display: inline-block;
            width: 120px;
            margin: 5px;
            vertical-align: top;
            font-size: 12px;
            font-family: Arial, sans-serif;
            text-align: center;
        }

        .scarab-item img {
            max-width: 100px;
            max-height: 100px;
            display: block;
            margin: 0px auto;
            border: 0px;
        }

        .scarab-prev, .scarab-next {
            position: absolute;
            width: 20px;
            height: 20px;
            line-height: 20px;
            top: 50%;
            margin-top: -10px;
            cursor: pointer;
            text-align: center;
            font-size: 16px;
            color: #C5D7EF;
        }

        .scarab-prev {
            left: 0px;
        }

        .scarab-next {
            right: 0px;
        }

        .scarab-disabled-button {
            cursor: default;
            opacity: 0.4;
        }
    </style>
<?php endif; //if ($pageHandleData['status'] == 'Valid') ?>
