<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */

/** @var \Emartech\EmarsysRecommender\Block\JavascriptTracking $block */
?>

<?php $merchantId = $block->getMerchantId(); ?>
<?php $webExtendStatus = $block->getJsEnableStatusForAllPages(); ?>

<!-- This code will embeded on all pages -->
<?php if ($webExtendStatus && !empty($merchantId)): ?>
    <div id="webextend-code"></div>
    <script>
        require([
            'jquery'
        ], function (jQuery) {
            jQuery.ajax({
                url: '<?php echo $block->getAjaxUpdateUrl() ?>',
                data: {
                    'unique_key': Math.floor((Math.random() * 1000000) + 1),
                    'full_action_name': '<?php echo $block->getPageHandle(); ?>'
                },
                type: 'GET',
                dataType: 'json',
                success: function (result) {
                    if (result.status == 1) {
                        <?php if ($currentCategory = $block->getCurrentCategory()): ?>
                        ScarabQueue.push(['category', '<?php echo $currentCategory; ?>']);
                        <?php endif; ?>

                        <?php if ($currentProduct = $block->getCurrentProductSku()): ?>
                        ScarabQueue.push(['view', '<?php echo $currentProduct; ?>']);
                        <?php endif; ?>

                        <?php if ($searchResult = $block->getSearchResult()): ?>
                        ScarabQueue.push(['searchTerm', '<?php echo $searchResult; ?>']);
                        <?php endif; ?>

                        <?php if ($storeCode = $block->getStoreCode()): ?>
                        ScarabQueue.push(['availabilityZone', '<?php echo $storeCode ?>']);
                        <?php endif; ?>

                        jQuery('#webextend-code').html(result.content);
                        ScarabQueue.push(['go']);
                    }
                },
                error: function (xhr, textStatus, thrownError) {
                    console.log("Emarsys WebExtend Ajax Error: " + thrownError);
                }
            });
        });
    </script>
<?php endif; ?>
