<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */

/** @var \Emartech\EmarsysRecommender\Block\JavascriptTracking $block */
?>

<?php $merchantId = $block->getMerchantId(); ?>
<?php $webExtendStatus = $block->getJsEnableStatusForAllPages(); ?>

<!-- This code will embeded on all pages -->
<?php if ($webExtendStatus && !empty($merchantId)): ?>
    <div id="webextend-code"></div>
    <script>
        require([
            'jquery'
        ], function (jQuery) {
            jQuery.ajax({
                url: '<?php echo $block->getAjaxUpdateUrl() ?>',
                data: {
                    'unique_key': Math.random() * Math.random(),
                    'full_action_name': '<?php echo $block->getPageHandle(); ?>'
                },
                type: 'GET',
                dataType: 'json',
                success: function (result) {
                    if (result.status == 1) {
                        jQuery('#webextend-code').html(result.content);
                    }
                },
                error: function (xhr, textStatus, thrownError) {
                    console.log("Emarsys WebExtend Ajax Error: " + thrownError);
                }
            });

            <?php if (false): ?>
                var miniCart = jQuery('[data-block=\'minicart\']');
                miniCart.on('cartUpdated', function () {
                    jQuery.ajax({
                        url: '<?php echo $block->getAjaxUpdateCartUrl() ?>',
                        data: {
                            'unique_key': Math.random() * Math.random(),
                            'full_action_name': '<?php echo $block->getPageHandle(); ?>'
                        },
                        type: 'GET',
                        dataType: 'json',
                        success: function (result) {
                            if (result.status == 1) {
                                jQuery('#webextend-code').html(result.content);
                            }
                        },
                        error: function (xhr, textStatus, thrownError) {
                            console.log("Emarsys WebExtend Ajax Error: " + thrownError);
                        }
                    });
                });
            <?php endif; ?>
        });
    </script>
<?php endif; ?>




